services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: prolink-skhu
    container_name: prolink-skhu
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      APP_SERVER_URL: ${APP_SERVER_URL}
    depends_on:
      - mongo
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
